version: 2.1
orbs:
  allure: ayte/allure@0.1.2
jobs:
  updateSnapshot:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test -u
      - run: |
          git config --global user.email "CircleCI@example.com"
          git config --global user.name "CircleCI"
          git config --global push.default current
          git add .
          git commit -m "CI. Update snapshot"
          git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/zaqqaz/progressive-tests.git ${CIRCLE_BRANCH}
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo

    steps:
      - run: google-chrome --version
      - checkout
      - allure/install

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run:
          name: Generate report
          when: on_fail
          command: allure generate

      - allure/report
workflows:
  version: 2.1
  workflow:
    jobs:
    - build
    - "Update snapshot?": # <<< A job that will require manual approval in the CircleCI web application.
        type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
    # On approval of the `hold` job, any successive job that requires the `hold` job will run.
    # In this case, a user is manually triggering the deploy job.
    - updateSnapshot:
        requires:
          - "Update snapshot?"
